### ISSUE TITLE
[FEAT] api/card get요청 API 수정 제안

### ISSUE THREAD

**Issue by YeonSeong-Lee** [NOON-official/scheduling_server#18]
현재 http://localhost:5000/api/card get요청시에 모든 카드 정보가 들어옵니다. 

isDeleted : true 인 데이터는 안 보내줘도 데이터인거 같아
데이터 통신 비용을 아낄겸 API 수정 제안드립니다.

**Comment by MoonGyu1** [comment]
모든 카드 정보가 들어온다는 것이 카드의 불필요한 정보도 같이 조회된다는 말씀이신가요 아니면 삭제된 카드도 같이 조회된다는 의미인가요??
만약 후자라면 로직 자체는 삭제되지 않은(is_deleted=false)인 카드만 반환되도록 했는데 문제 생기는 부분 알려주시면 다시 한 번 확인해보겠습니다!
전자라면 조회하시고 싶은 프로퍼티만 알려주시면 API 수정해보겠습니다~!

**Comment by YeonSeong-Lee** [comment]
후자가 맞습니다!!!

**Comment by YeonSeong-Lee** [comment]
.... 다음에는 좀 더 확인해보고 요청 올릴게요..**🥲**
